{% set name = "apsg" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfaea724ae373ad75cbcc152bf8b2303f8e16bb770978c0e21248b807437bad5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - iapsg=apsg.shell:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base >=3.0

test:
  imports:
    - apsg

about:
  home: https://github.com/ondrolexa/apsg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: APSG - python package for structural geologists
  description: |
    APSG defines several new python classes to easily manage, analyze
    and visualize orientational structural geology data.
  doc_url: https://apsg.readthedocs.io
  dev_url: https://github.com/ondrolexa/apsg

extra:
  recipe-maintainers:
    - ondrolexa
