{% set name = "apsg" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0537677543cc55bb45cac947d18f96e5c28ef82ae9d16f14915e37859082a1f6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"
  entry_points:
    - iapsg=apsg.shell:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - apsg

about:
  home: https://github.com/ondrolexa/apsg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'APSG - python package for structural geologists'
  description: |
    APSG defines several new python classes to easily manage, analyze
    and visualize orientational structural geology data.
  doc_url: https://apsg.readthedocs.io/
  dev_url: https://github.com/ondrolexa/apsg

extra:
  recipe-maintainers:
    - ondrolexa
