{% set name = "apsg" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c49e5bbd09ce86a939fd6d5643fdc7bac48142c4d352e3f1be7c02521ed4a2bf

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - iapsg=apsg.shell:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base >=3.0

test:
  imports:
    - apsg

about:
  home: https://github.com/ondrolexa/apsg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'APSG - python package for structural geologists'
  description: |
    APSG defines several new python classes to easily manage, analyze
    and visualize orientational structural geology data.
  doc_url: https://apsg.readthedocs.io
  dev_url: https://github.com/ondrolexa/apsg

extra:
  recipe-maintainers:
    - ondrolexa
