{% set name = "apsg" %}
{% set version = "1.3.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f748ddf0ee7eae026e34e3915fcb2df57bd3f45368d3937b77cc2c80e9d7af6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - iapsg=apsg.shell:main

requirements:
  build:
    - python >={{ python_min }}
    - pip
    - poetry
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base >=3.0
    - sqlalchemy
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - apsg

about:
  home: https://github.com/ondrolexa/apsg
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: APSG - python package for structural geologists
  description: |
    APSG defines several new python classes to easily manage, analyze
    and visualize orientational structural geology data.
  doc_url: https://apsg.readthedocs.io
  dev_url: https://github.com/ondrolexa/apsg

extra:
  recipe-maintainers:
    - ondrolexa
